### ISSUE TITLE
TERMS OF USE

### ISSUE THREAD

**Issue by cara-lgrow** [citizenlabsgr/adopt-a-drain#227] opened 2019-04-12 14:06 UTC
The terms of use is NOT updated and consistent with what I have posted on the google drive. Please fix ASAP. This worries me as the sight is live, and the legal terms are not correct.

**Comment by beyondtheteal** [comment] 2019-04-16 22:40
#229

**Comment by cara-lgrow** [comment] 2019-05-03 16:39
this is now updated in the staging app. needs to be pushed to production

**Comment by Wilfongjt** [comment] 2019-05-06 18:36
duplicate of 229

**Closed by Wilfongjt** 2019-05-06 18:37 UTC
Labels: Priority-1, in progress
