### ISSUE TITLE
Change thumbnail image from SF program

### ISSUE THREAD

**Issue by cara-lgrow** [citizenlabsgr/adopt-a-drain#224] opened 2019-04-09 17:52 UTC
The thumbnail image that shows up for the LGROW site is SF's image. Can we also change the text that goes along with it?

See James' link to the program in slack...SF's logo pops up, with canned text that is incorrect. 
We need this fixed before we can share the program anywhere online.

**Comment by Wilfongjt** [comment] 2019-05-06 18:39
duplicate of 196

**Closed by Wilfongjt** 2019-05-06 18:39 UTC
Labels: Priority-1
