### ISSUE TITLE
Need a resolution for naughty drain names

### ISSUE THREAD

**Issue by cara-lgrow** [citizenlabsgr/adopt-a-drain#205] opened 2019-03-22 14:11 UTC
James- you had mentioned that it looked like there was some code to filter out inappropriate word from drain names. I was able to adopt drains with cuss words. Is there any way to resolve this?

**Comment by beyondtheteal** [comment] 2019-04-03 02:44
I was looking into what gem we might use for this when I found this article talking about how complex this issue is: https://blog.codinghorror.com/obscenity-filters-bad-idea-or-incredibly-intercoursing-bad-idea/ 

This is one of the top profanity filters: https://github.com/mobomo/profanity_filter 
But their dictionary is....both too inclusive and not very inclusive at all. https://github.com/mobomo/profanity_filter/blob/master/config/dictionary.yml 

What if Dick Cheney wanted to name his drain `Dick Cheney Jr.`? Not allowed. 
But if someone wanted to call it `d1ck`, it would be allowed by this filter. 

Can we brainstorm a way around this that doesn't involve a programmatic block or censor?

**Comment by Wilfongjt** [comment] 2019-08-06 23:37
duplicate of #231

**Closed by Wilfongjt** 2019-08-06 23:37 UTC
Labels: Priority-2
