### ISSUE TITLE
Terms & Conditions (Duplicate)

### ISSUE THREAD

**Issue by CourtneyCromley** [citizenlabsgr/adopt-a-drain#103] opened 2019-01-22 20:36 UTC
Terms and conditions have been updated and added to the google Doc. Could you please update this on AAD asap? We want it updated when we ask the communities to look at the website.

**Comment by Wilfongjt** [comment] 2019-01-25 19:33
this is a duplicate of #35

**Comment by CourtneyCromley** [comment] 2019-01-25 19:35
Would you like me to delete this one? We have changed around a few things on our terms of service. I will email you the final copy next week. I would like to send you the word document to keep it in a consistent format.

**Comment by Wilfongjt** [comment] 2019-01-26 10:05
No need to send the word document.  The google doc is more universal and we don't want competing copies floating around out there.

**Closed** 2019-03-06 01:19 UTC
